name: flutter_availability
description: "Flutter availability userstory package"
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0
  flutter_hooks: ^0.20.5
  flutter_availability_data_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_availability
      ref: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0

flutter:
