name: flutter_availability_data_interface
description: "The data interface for the flutter_availability component"
version: 1.0.0

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dev_dependencies:
  test: ^1.16.0
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
